name: Continuous integration

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Code style
        run: npm run lint

      - name: Run Test
        run: npm run runtest
      
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: code-test-report
          path: cypress/reports/*
